courses/urls.py
from django.conf.urls import url
from rest_framework import routers

from .views import courses_views, api


app_name = 'courses'
router = routers.DefaultRouter()
router.register(r'courses', api.CourseViewSet)
router.register(r'departments', api.DepartmentViewSet)
router.register(r'course_groups', api.CourseGroupViewSet, base_name='course_group')
router.register(r'students', api.StudentViewSet)

urlpatterns = [
    url(r'^$', courses_views.search, name='search'),
    url(r'^delete/(?P<course_group_id>[\d]+)/$', courses_views.delete_course_group, name='delete'),
    url(r'^add/$', courses_views.add, name='add'),
    url(r'^edit/(?P<course_id>[0-9]+)/$', courses_views.edit_detail, name='edit_detail'),
]

examplus/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView

from .routers import DefaultRouter
from courses.urls import router as course_router
from exams.urls import router as exam_router
from user_panel.urls import router as user_router
from user_panel.views.panel import index

router = DefaultRouter()
router.extend(exam_router)
router.extend(course_router)
router.extend(user_router)

urlpatterns = [
    url(r'^$', RedirectView.as_view(url='/exams/'), name='home'),
    url(r'^faq/$', index, name='faq'),
    url(r'^api/v1/', include(router.urls, namespace='api')),
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^exams/', include('exams.urls')),
    url(r'^courses/', include('courses.urls')),
    url(r'^user/', include('user_panel.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^grappelli/', include('grappelli.urls')),
]

exams/urls.py
from django.conf.urls import url
from rest_framework import routers

from .views import exams_views, api, questions_views


app_name = 'exams'
router = routers.DefaultRouter()
router.register(r'exams', api.ExamsViewSet, base_name='exams')
router.register(r'question_set', api.QuestionSetViewSet)
router.register(r'question', api.QuestionViewSet)
router.register(r'exam_slugs', api.ExamsSlugViewSet)

urlpatterns = [
    url(r'^$', exams_views.search, name='search'),
    url(r'^edit/(?P<exam_id>[0-9]+)/$', exams_views.edit_detail, name='edit_detail'),
    url(r'^get/csv/(?P<exam>[0-9]+)/$', exams_views.download_exam_csv, name='download'),
    url(r'^start/(?P<exam_id>[0-9]+)/$', exams_views.start_exam, name='start_exam'),
    url(r'^panel/(?P<exam_id>[0-9]+)/$', exams_views.start_exam_panel, name='start_exam_panel'),
    url(r'^execution/(?P<exam_id>[0-9]+)/$', exams_views.execution, name='execution'),
    url(r'^add/$', exams_views.add, name='add'),
    url(r'^student/(?P<slug>[\w]+)/$', exams_views.student_panel, name='student_panel'),
    url(r'^student/(?P<slug_student>[\w]+)/exam/(?P<slug_exam>[\w]+)/$', exams_views.exam_panel, name='student_exam_panel'),
    url(r'^student/(?P<slug_student>[\w]+)/exam/(?P<slug_exam>[\w]+)/start/$', exams_views.start_exam_student, name='student_exam_start'),
    url(r'^student/(?P<slug_student>[\w]+)/exam/(?P<slug_exam>[\w]+)/end/$', exams_views.end_exam, name='student_exam_end'),
    url(r'^student/(?P<slug_student>[\w]+)/exam/(?P<slug_exam>[\w]+)/(?P<nr>[\d]+)/$', exams_views.exam_question, name='exam_question'),
    url(r'^questions/add/$', questions_views.add, name='question_add'),
    url(r'^questions/search/$', questions_views.search, name='question_search'),
    url(r'^questions/edit/(?P<question_set>[0-9]+)/$', questions_views.edit, name='question_edit'),
    url(r'^delete/(?P<exam_id>[\d]+)/$', exams_views.delete_exam, name='delete'),
]

user_panel/urls.py
from django.conf.urls import url
from rest_framework import routers

from .views import panel


app_name = 'user_panel'

router = routers.DefaultRouter()


urlpatterns = [
    url(r'^$', panel.panel, name='panel'),
]

templates/common/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}Exam-plus{% endblock %}</title>
    {% load static %}
    <script src="/static/libs/jquery/dist/jquery.min.js"></script>
    <script src="/static/libs/semantic-ui/dist/semantic.min.js"></script>
    <script src="/static/common/js/base.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'libs/semantic-ui/dist/semantic.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'common/css/base.css' %}" />

    {% block extra_js %}{% endblock extra_js %}
    {% block extra_css %}{% endblock extra_css %}
    {% block extra_head %}{% endblock extra_head %}
  </head>
  <body>
    {% if user.is_authenticated %}
      <div class="ui sidebar vertical large left inverted menu">
        <div class="item">
          <a class="item" href="{% url 'exams:search' %}"><img src="/static/logo.png" alt="ExamPlus"></a>
        </div>
        <div class="item">
          <h4 class="ui inverted blue header">Kursy i studenci</h4>
          <div class="menu">
            <a class="item" href="{% url 'courses:add' %}">
              <i class="block add user icon"></i>
              Dodaj listę studentów
            </a>
            <a class="item" href="{% url 'courses:search' %}">
              <i class="block tasks icon"></i>
              Przeglądaj kursy
            </a>
          </div>
        </div>
        <div class="item">
          <h4 class="ui inverted blue header">Zestawy pytań</h4>
          <div class="menu">
            <a class="item" href="{% url 'exams:question_add' %}">
              <i class="block upload icon"></i>
              Dodaj zestaw
            </a>
            <a class="item" href="{% url 'exams:question_search' %}">
              <i class="block file text outline icon"></i>
              Przeglądaj zestawy
            </a>
          </div>
        </div>
        <div class="item">
          <h4 class="ui inverted blue header">Egzaminy</h4>
          <div class="menu">
            <a class="item" href="{% url 'exams:add' %}">
              <i class="block calendar icon"></i>
              Nowy egzamin
            </a>
            <a class="item" href="{% url 'exams:search' %}">
              <i class="block laptop icon"></i>
              Przeglądaj egzaminy
            </a>
          </div>
        </div>
        <div class="item">
          <h4 class="ui inverted blue header">Ustawienia</h4>
          <div class="menu">
            <a class="item" href="{% url 'user_panel:panel' %}">
              <i class="block setting icon"></i>
              Preferencje
            </a>
            <a class="item" href="{% url 'faq' %}">
              FAQ
            </a>
          </div>
        </div>
      </div>
    {% endif %}
    <div class="pusher">
    <div class="wrap-exam">
      {% block nav %}
        {% if user.is_authenticated %}
          <div class="ui top fixed menu">
            <div class="item" id="toggle">
              <i class="sidebar icon"></i>
              Menu
            </div>
            <div class="right menu">
              <div class="item">
                <div class="ui transparent icon input">
                  <form action="{% url 'exams:search' %}" method="get">
                    <input name="search" type="text" placeholder="Szukaj egzaminu...">
                    <i class="search link icon"></i>
                  </form>
                </div>
              </div>
              <a class="item" href="{% url 'logout' %}">Wyloguj</a>
            </div>
          </div>
      {% endif %}
    {% endblock nav %}
      <div class="container main-body">
        {% block page_header %}{% endblock page_header %}
        {% block sidebar %}{% endblock sidebar %}
        {% if user.is_authenticated %}
          <div class="ui breadcrumb">
            {% block breadcrumb_home %}
              <a class="section" href="{% url 'exams:search' %}"><i class="home icon"></i></a>
              <span class="divider">/</span>
            {% endblock breadcrumb_home %}
            {% block breadcrumb %}
            {% endblock breadcrumb %}
          </div>
        {% endif %}
        {% block content %}{% endblock content %}
      </div>
    </div>
    </div>
    {% block bottom_js %}
    <script type="text/javascript">
      $('#toggle').click(function(){
        $('.ui.sidebar').sidebar('toggle');
      });
    </script>
    {% endblock bottom_js %}
  </body>
</html>