examplus/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView

from .routers import DefaultRouter
from courses.urls import router as course_router
from exams.urls import router as exam_router
from user_panel.urls import router as user_router
from user_panel.views.panel import index

router = DefaultRouter()
router.extend(exam_router)
router.extend(course_router)
router.extend(user_router)

urlpatterns = [
    url(r'^$', RedirectView.as_view(url='/exams/'), name='home'),
    url(r'^faq/$', index, name='faq'),
    url(r'^api/v1/', include(router.urls, namespace='api')),
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^exams/', include('exams.urls')),
    url(r'^courses/', include('courses.urls')),
    url(r'^user/', include('user_panel.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^grappelli/', include('grappelli.urls')),
]

exams/urls.py
from django.conf.urls import url
from rest_framework import routers

from .views import exams_views, api, questions_views


app_name = 'exams'
router = routers.DefaultRouter()
router.register(r'exams', api.ExamsViewSet, base_name='exams')
router.register(r'question_set', api.QuestionSetViewSet)
router.register(r'question', api.QuestionViewSet)
router.register(r'exam_slugs', api.ExamsSlugViewSet)

urlpatterns = [
    url(r'^$', exams_views.search, name='search'),
    url(r'^edit/(?P<exam_id>[0-9]+)/$', exams_views.edit_detail, name='edit_detail'),
    url(r'^get/csv/(?P<exam>[0-9]+)/$', exams_views.download_exam_csv, name='download'),
    url(r'^start/(?P<exam_id>[0-9]+)/$', exams_views.start_exam, name='start_exam'),
    url(r'^panel/(?P<exam_id>[0-9]+)/$', exams_views.start_exam_panel, name='start_exam_panel'),
    url(r'^execution/(?P<exam_id>[0-9]+)/$', exams_views.execution, name='execution'),
    url(r'^add/$', exams_views.add, name='add'),
    url(r'^student/(?P<slug>[\w]+)/$', exams_views.student_panel, name='student_panel'),
    url(r'^student/(?P<slug_student>[\w]+)/exam/(?P<slug_exam>[\w]+)/$', exams_views.exam_panel, name='student_exam_panel'),
    url(r'^student/(?P<slug_student>[\w]+)/exam/(?P<slug_exam>[\w]+)/start/$', exams_views.start_exam_student, name='student_exam_start'),
    url(r'^student/(?P<slug_student>[\w]+)/exam/(?P<slug_exam>[\w]+)/end/$', exams_views.end_exam, name='student_exam_end'),
    url(r'^student/(?P<slug_student>[\w]+)/exam/(?P<slug_exam>[\w]+)/(?P<nr>[\d]+)/$', exams_views.exam_question, name='exam_question'),
    url(r'^questions/add/$', questions_views.add, name='question_add'),
    url(r'^questions/search/$', questions_views.search, name='question_search'),
    url(r'^questions/edit/(?P<question_set>[0-9]+)/$', questions_views.edit, name='question_edit'),
    url(r'^delete/(?P<exam_id>[\d]+)/$', exams_views.delete_exam, name='delete'),
]

exams/views/api.py
from django.contrib.auth import get_user
from django.db.models import F, Q, Sum
from rest_framework import viewsets, filters
from rest_framework.decorators import list_route
from rest_framework.response import Response

from exams.models import Exam, QuestionSet, Question, ExamSlug
from exams.serializers import ExamSerializer, QuestionSetSerializer, \
    QuestionSetAjaxSerializer, QuestionSerializer, ExamSlugSerializer


class ExamFilter(filters.BaseFilterBackend):
    def filter_queryset(self, request, queryset, view):
        name = request.GET.get('name')
        if name:
            queryset = queryset.filter(name__icontains=name)
        return queryset.filter(owner=get_user(request))


class ExamSlugFilter(filters.BaseFilterBackend):
    def filter_queryset(self, request, queryset, view):
        if 'in_progress' in request.GET:
            queryset = queryset.filter(status__in=[ExamSlug.IN_PROGRESS, ExamSlug.FINISHED])
        name = request.GET.get('name')
        if name:
            queryset = queryset.filter(
                Q(student__first_name__icontains=name) |
                Q(student__last_name__icontains=name) |
                Q(student__index__icontains=name))
        exam_id = request.GET.get('exam')
        return queryset.filter(exam__id=exam_id)


class QuestionSetFilter(filters.BaseFilterBackend):
    def filter_queryset(self, request, queryset, view):
        name = request.GET.get('name')
        if name:
            queryset = queryset.filter(name__icontains=name)
        return queryset.filter(owner=get_user(request))


class QuestionFilter(filters.BaseFilterBackend):
    def filter_queryset(self, request, queryset, view):
        desctription = request.GET.get('desctription')
        if desctription:
            queryset = queryset.filter(desctription__icontains=desctription)
        question_set = request.GET.get('question_set') or 0
        return queryset.filter(question_set=question_set)


class ExamsViewSet(viewsets.ModelViewSet):
    serializer_class = ExamSerializer
    filter_backends = (filters.OrderingFilter, ExamFilter)

    def get_queryset(self):
        return Exam.objects.filter(owner=get_user(self.request)).annotate(
            course_name=F('course_group__course__name'),
            department=F('course_group__course__department__name'))


class ExamsSlugViewSet(viewsets.ModelViewSet):
    serializer_class = ExamSlugSerializer
    filter_backends = (filters.OrderingFilter, ExamSlugFilter)

    queryset = ExamSlug.objects.annotate(
        student_first_name=F('student__first_name'),
        student_last_name=F('student__last_name'),
        student_index=F('student__index'),
        answers_sum=Sum('answers__result'),)


class QuestionSetViewSet(viewsets.ModelViewSet):
    queryset = QuestionSet.objects.all()
    serializer_class = QuestionSetSerializer
    filter_backends = (filters.OrderingFilter, QuestionSetFilter)

    @list_route()
    def ajax(self, request):
        questionsets = QuestionSet.objects.filter(owner=get_user(request))
        if 'name' in request.GET:
            questionsets = questionsets.filter(name__icontains=request.GET['name'])
        serializer = QuestionSetAjaxSerializer(questionsets, many=True)
        return Response({'results': serializer.data})


class QuestionViewSet(viewsets.ModelViewSet):
    queryset = Question.objects.all()
    serializer_class = QuestionSerializer
    filter_backends = (filters.OrderingFilter, QuestionFilter)

exams/views/exams_views.py
import logging
from datetime import datetime

from django.conf import settings
from django.contrib.auth import get_user
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.db.models import F, Case, Sum, When, IntegerField
from django.http import JsonResponse, Http404
from django.shortcuts import render, redirect, get_object_or_404, reverse

from courses.models import CourseGroup, Student
from exams.forms import AddExamForm, ExamEditForm
from exams.models import Exam, ExamSlug, Answer
from exams.services import ExamService


logger = logging.getLogger(__name__)


@login_required
def search(request):
    return render(request, 'exams/search/index.html')


@login_required
def add(request):
    if request.method == 'POST':
        form = AddExamForm(request.POST)
        if form.is_valid():
            new_exam = form.save(commit=False)
            new_exam.owner = get_user(request)
            new_exam.save()
            return redirect('exams:edit_detail', new_exam.id)
    return render(request, 'exams/add/index.html')


@login_required
def edit_detail(request, exam_id):
    exam = get_object_or_404(Exam, pk=exam_id)
    if request.method == 'POST':
        if 'key' in request.POST and 'data' in request.POST:
            key = request.POST['key']
            data = request.POST['data']
            changed = ''
            if key.startswith('update'):
                if '_grade' in key:
                    exam.grade[key[13:]] = int(data)
                    exam.save()
                    changed = ''
                    grades = sorted(exam.grade.items())
                    last = grades[-1]
                    for grade, score in sorted(exam.grade.items()):
                        changed += grade + ': ' + str(score) + '% '
                        if grade != last[0]:
                            changed += ' | '
                    return JsonResponse({"success": "1", "changed": changed})
                if '_date' in key:
                    data = datetime.strptime(data, '%B %d, %Y %H:%M')
                    changed = data.strftime('%B %-d, %Y %H:%M')
                elif 'course_group' in key:
                    data = get_object_or_404(CourseGroup, pk=data)
                    changed = data.name
                setattr(exam, key[7:], data)
                exam.save()
                changed = getattr(exam, key[7:]) if not changed else changed
            elif key == 'add_student_single':
                exam.students.add(int(data))
            elif key == 'remove_student':
                exam.students.remove(int(data))
                ExamSlug.objects.filter(exam=exam, student__id=data).delete()
                Answer.objects.filter(exam=exam, student__id=data).delete()
            elif key == 'generate':
                ExamService.generate_exams(exam)
            elif key == 'send_links':
                slugs = exam.slugs.filter(student__in=exam.students.all(), email_sent=False)
                for slug in slugs:
                    link = reverse('exams:student_exam_panel', args=[slug.student.slug, slug.slug])
                    recip = slug.student.index[-6:] + settings.PWR_EMAIL
                    send_mail(
                        'Egzamin',
                        'Egzamin o godzine: %s, w sali %s, z kursu: %s, link: https://156.17.42.121%s' % (
                            slug.exam.start_date, exam.class_room, exam.course_group.name, link),
                        settings.EMAIL_HOST_USER,
                        [recip],
                        fail_silently=False,
                    )
                    slug.email_sent = True
                    slug.save()
                    logger.info('email sent to %s' % recip)
            elif key == 'add_student_all':
                students = Student.objects.filter(course_group=exam.course_group, is_blocked=False)
                exam.students.add(*students)
            elif key == 'add_student_re':
                pass
        return JsonResponse({"success": "1", "changed": changed})
    try:
        grades = sorted(exam.grade.items())
    except AttributeError:
        grades = sorted({'3.0': 50, '3.5': 60, '4.0': 70, '4.5': 80, '5.0': 90, '5.5': 95}.items())
    form = ExamEditForm(instance=exam)
    email_button = True if ExamSlug.objects.filter(exam=exam, email_sent=False, student__in=exam.students.all()) else False
    return render(request, 'exams/edit_detail/index.html', {'exam': exam, 'grades': grades, 'form': form, 'email_button': email_button})


def student_panel(request, slug):
    student = get_object_or_404(Student, slug=slug)
    exams = Exam.objects.filter(students=student, slugs__student=student).annotate(
        slug=F('slugs__slug'),
        points=Sum(Case(When(answers__student=student, then=F('answers__result')), output_field=IntegerField())))
    for exam in exams:
        max_points = exam.question_count
        percent_score = (exam.points / max_points) * 100
        try:
            items = sorted({k: v for k, v in exam.grade.items() if v <= percent_score})
        except AttributeError:
            items = None
        exam.student_grade = '2.0' if not items else items[-1]
    return render(request, 'exams/panel/index.html', {'student': student, 'exams': exams})


def exam_panel(request, slug_student, slug_exam):
    exam_slug = get_object_or_404(ExamSlug, slug=slug_exam)
    student = get_object_or_404(Student, slug=slug_student)
    if student != exam_slug.student:
        raise Http404("Strona nie istnieje, sprawdź jeszcze raz link")
    if exam_slug.status == ExamSlug.IN_PROGRESS:
        questions = Answer.objects.filter(student=student, exam=exam_slug.exam).only('answer', 'id')
    else:
        questions = None
    return render(request, 'exams/exam/index.html', {
        'student': student,
        'slug_exam': slug_exam,
        'questions': questions,
        'finished': True if exam_slug.status == ExamSlug.FINISHED else False})


def start_exam_student(request, slug_student, slug_exam):
    exam_slug = get_object_or_404(ExamSlug, slug=slug_exam)
    if exam_slug.status == ExamSlug.IN_PROGRESS and exam_slug.exam.can_start:
        return redirect('exams:exam_question', slug_student, slug_exam, 1)
    return redirect('exams:student_exam_panel', slug_student, slug_exam)


def start_exam_panel(request, exam_id):
    exam = get_object_or_404(Exam, pk=exam_id)
    if request.method == 'POST':
        if 'exam_slug_id' in request.POST:
            exam_slug_id = request.POST['exam_slug_id']
            exam_slug = get_object_or_404(ExamSlug, id=exam_slug_id)
            if exam_slug.status is not ExamSlug.IN_PROGRESS:
                exam_slug.status = ExamSlug.IN_PROGRESS
            else:
                exam_slug.status = ExamSlug.NEW
            exam_slug.save()
            return JsonResponse({"success": "1", })
        if 'add_all' in request.POST:
            for slug in exam.slugs.all():
                slug.status = ExamSlug.IN_PROGRESS
                slug.save()
            return JsonResponse({"success": "1", })
    if exam.can_start is True:
        return redirect('exams:execution', exam.id)
    return render(request, 'exams/start/index.html', {'exam': exam})


def start_exam(request, exam_id):
    exam = get_object_or_404(Exam, pk=exam_id)
    exam.can_start = True
    exam.save()
    return redirect('exams:execution', exam.id)


def execution(request, exam_id):
    import json
    exam = get_object_or_404(Exam, pk=exam_id)
    try:
        grades = json.dumps(exam.grade)
    except AttributeError:
        grades = json.dumps({'3.0': 50, '3.5': 60, '4.0': 70, '4.5': 80, '5.0': 90, '5.5': 95})
    return render(request, 'exams/execution/index.html', {'exam': exam, 'grades': grades})


def end_exam(request, slug_student, slug_exam):
    exam_slug = get_object_or_404(ExamSlug, slug=slug_exam)
    exam_slug.status = ExamSlug.FINISHED
    exam_slug.save()
    return redirect('exams:student_panel', slug_student)


def exam_question(request, slug_student, slug_exam, nr):
    exam_slug = get_object_or_404(ExamSlug, slug=slug_exam)
    student = get_object_or_404(Student, slug=slug_student)
    if student != exam_slug.student:
        raise Http404("Strona nie istnieje, sprawdź jeszcze raz link")
    nr = int(nr)
    q_count = Answer.objects.filter(student=student, exam=exam_slug.exam).count()
    if nr < 1 or nr > q_count:
        raise Http404("Pytanie nie istnieje")
    answer = Answer.objects.filter(student=student, exam=exam_slug.exam)[nr - 1]
    if request.method == 'POST':
        if 'key' in request.POST and 'data' in request.POST:
            choice = answer.question.choices[request.POST['data']]
            if request.POST['key'] == 'check':
                answer.result = int(choice['points'])
                answer.answer = choice['id']
            # else:
            #     answer.result = int(choice['points'])
                answer.save()
        return JsonResponse({"success": "1", })
    selected = '' if answer.answer == '' else int(answer.answer)
    page = {'has_next': 1 if q_count > nr else 0, 'has_prev': 0 if nr <= 1 else 1, 'next': nr + 1, 'prev': nr - 1}
    return render(request, 'exams/question/index.html', {
        'student': student,
        'nr': nr,
        'slug_exam': slug_exam,
        'question': answer.question,
        'page': page,
        'selected': selected,
    })


@login_required
def delete_exam(request, exam_id):
    exam = get_object_or_404(Exam, pk=exam_id)
    exam.delete()
    return redirect('exams:search')


@login_required
def download_exam_csv(request, exam):
    return ExamService.get_exam_csv(exam)

exams/templates/exams/edit_detail/index.html
{% extends "common/base.html" %}

{% load static %}

{% block extra_css %}
  <link rel="stylesheet" type="text/css" href="{% static 'libs/datatables.net-se/css/dataTables.semanticui.min.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'libs/semantic-ui-calendar/dist/calendar.min.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'exams/css/edit-detail.css' %}" />
{% endblock extra_css %}

{% block extra_js %}
  <script src="/static/libs/datatables.net/js/jquery.dataTables.min.js"></script>
  <script src="/static/libs/datatables.net-se/js/dataTables.semanticui.min.js"></script>
  <script src="/static/libs/semantic-ui-calendar/dist/calendar.min.js"></script>
  <script src="/static/exams/js/edit-detail.js"></script>
{% endblock extra_js %}

{% block breadcrumb %}
  <a class="section" href="{% url 'exams:search' %}">Egazaminy</a>
  <span class="divider">/</span>
  <div class="section active">{{exam.name}}</div>
{% endblock breadcrumb %}

{%block content%}
  <script type="text/javascript">
    var exam_id = '{{exam.id}}';
  </script>
  <div class="ui segments">
    <div class="ui segment">
      <p>Edycja egzaminu {{exam.name}}</p>
    </div>
    <div class="ui segment">
      <table class="ui very basic table selectable">
        <tbody>
          {% for field in form %}
            <tr>
              <td>{{field.label}}</td>
              <td class="text_display">{{field.value}}</td>
              <td>{{field}}</td>
            </tr>
          {% endfor %}
          <tr>
            <td>Skala ocen</td>
            <td class="text_display">{% for grade, score in grades %}{{grade}}: {{score}}%{% if not forloop.last %} | {% endif %}{% endfor %}</td>
            <td>
              <a class='popup_btn'>Edytuj</a>
              <div class="ui popup transition hidden" data-position="left center">
                <div class="ui grid paddings-label">
                  {% for grade, score in grades %}
                    <div class="row">
                      <div class="ui action input">
                        <input type="text" placeholder="Wynik w %" name="grade_{{grade}}" value="{{score}}">
                        <button class="ui teal right labeled icon button update_param">
                        <i class="edit icon"></i>
                          Ocena {{grade}}
                        </button>
                      </div>
                    </div>
                  {% endfor %}
                </div>
              </div>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="ui segment">
      <p>Zapisani studenci</p>
    </div>
    <div class="ui segment">
      <table id="students" class="ui selectable striped celled table" cellspacing="0" width="100%"></table>
    </div>
    <div class="ui segment">
      <p>Dodaj studentów</p>
      <div class="form_field ui search selection dropdown" id="students_dropdown">
        <input type="hidden" name="student"><i class="dropdown icon"></i>
        <div class="default text">Wybierz Studenta</div>
        <div class="menu"></div>
      </div>
      <button id='add_student_single' class="ui button">
        Dodaj wybranego
      </button>
      <button id='add_student_all' class="ui button update_btn">
        Dodaj wszystkich
      </button>
      <button id='add_student_re' class="ui button update_btn">
        Dodaj powtórkowe
      </button>
    </div>
    <div class="ui clearing segment">
      <a href="{% url 'exams:download' exam.id %}"><button class="ui right floated primary button">Raport CSV</button></a>
      <button id='delete_exam' class="ui right floated negative button">Usuń egzamin</button>
      <button id='send_links' class="ui right floated button" {% if not email_button %}disabled{% endif %}>Wyślij linki</button>
      <a href="{% url 'exams:start_exam_panel' exam.id %}"><button class="ui right floated positive button update_btn">{% if exam.can_start %}Panel egzaminu{% else %}Panel startu egzaminu{% endif %}</button></a>
      <button id='generate' class="ui right floated positive button update_btn">Generuj egzaminy</button>
    </div>
  </div>
  <div id="delete_student_modal" class="ui small modal">
    <div class="header">Usunięcie studenta z egzaminu</div>
    <div class="content">
      <span>Czy napewno chcesz usunąć</span>
      <span id='student_name'></span>
      <span>z kursu?</span>
    </div>
    <div class="actions">
      <div id='remove_student' class="ui positive button update_btn">Usuń</div>
      <div class="ui negative button">Zostaw</div>
    </div>
  </div>
  <div id="delete_exam_modal" class="ui small modal">
    <div class="header">Usuwanie egzaminu</div>
    <div class="content">
      <p>Czy napewno chcesz usunąć egzamin?</p>
    </div>
    <div class="actions">
      <a href="{% url 'exams:delete' exam.id %}">
        <div class="ui positive button">Usuń</div>
      </a>
      <div class="ui negative button">Zostaw</div>
    </div>
  </div>
{%endblock content%}